---
- name: Включить сценарий установки пакетов HAProxy и Keepalived
  import_tasks: install.yml
  tags:
    - install-lb
    - load-balancer

- name: Включить сценарий конфигурации сервисов и сетевых экранов
  import_tasks: configure.yml
  tags:
    - configure-lb
    - load-balancer

- name: Включить сценарий запуска и проверки доступности
  import_tasks: start.yml
  tags:
    - start-lb
    - load-balancer