---
- name: Создание бакета RustFS
  hosts: node
  gather_facts: false
  become: true
  tasks:
    - name: Создание целевого бакета
      ansible.builtin.import_role:
        name: rustfs_client
        tasks_from: create_bucket.yml